language: go
go:
  - 1.7
  - 1.8
  - 1.9
  - tip

go_import_path: github.com/daemonl/envconf.go

script:
  # run standard go tests
  - go vet ./...
  - go fmt ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)
